name: Deploy to GitHub Pages
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
        
      - uses: fastai/workflows/quarto-ghp@master
        with:
          # The python version that nbdev ci must run on must match the python version used 
          version: ${{ env.PYTHON_VERSION }}