# This workflow will install python dependencies, run tests and lint with a single version of python
# For more information see:
#  https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: rgxlog testing

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: get rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          # requirements file should include pytest, pycodestyle, mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e ./src/rgxlog-interpreter
          pip list
      - name: test pep8
        run: |
          pycodestyle --show-source --show-pep8 ./src/rgxlog-interpreter --config=./.pycodestyle
      - name: test mypy
        run: |
          mypy --ignore-missing-imports --install-types --non-interactive --disallow-untyped-defs ./src/rgxlog-interpreter
      - name: pytest
        run: |
          pytest ./src/rgxlog-interpreter/tests -s
