name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: loayshaqir/nbdev_ci_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install lsb_release
        run: sudo apt-get update && sudo apt-get install -y lsb-release
      - name: Activate conda environment
        run: |
          eval "$(conda shell.bash hook)"
          conda activate base  # replace 'base' with your specific environment name if different
      - name: Use nbdev CI Workflow
        uses: fastai/workflows/nbdev-ci@master