name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Activate conda environment
        run: |
          eval "$(conda shell.bash hook)"
          conda activate base
      - name: Print environment variables
        run: env
        
      - name: Print PATH
        run: echo $PATH
      
      - name: Use nbdev CI Workflow
        uses: fastai/workflows/nbdev-ci@master