name: CI
on: [workflow_dispatch, pull_request, push]

env:
  PYTHON_VERSION: 3.8

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Use nbdev CI Workflow
        uses: fastai/workflows/nbdev-ci@master
        with:
          # The python version that nbdev ci must run on must match the python version used 
          version: ${{ env.PYTHON_VERSION }}
          skip_test: true
          
      - name: Run Tests
        run: |
          test_output=$(python nbdev_test.py 2>&1)  # Capture both stdout and stderr
          echo "$test_output"  # Print the test output for debugging purposes
          
          if echo "$test_output" | grep -q "NameError:"; then
            echo "NameError found in test output"
            exit 1
          fi

          if echo "$test_output" | grep -q "nbdev Tests Failed On The Following Notebooks:"; then
            echo "nbdev Tests Failed"
            exit 1
          fi
        shell: bash