name: CI
on: [workflow_dispatch, pull_request, push]

env:
  PYTHON_VERSION: 3.8

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      - name: Use nbdev CI Workflow
        uses: fastai/workflows/nbdev-ci@master
        with:
          # The python version that nbdev ci must run on must match the python version used 
          version: ${{ env.PYTHON_VERSION }}
          skip_test: true
      - name: Test notebooks separately
        run: |
          python nbdev_test.py
