name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install RgxLog
        run: pip install -e spanner_workbench/src/rgxlog_interpreter
      - name: Use nbdev CI Workflow
        uses: fastai/workflows/nbdev-ci@master