name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install RgxLog
        run: |
          python -m pip install --upgrade pip
          pip install -e ./spanner_workbinterpreter
      - name: Use nbdev CI Workflow
        uses: fastai/workflows/nbdev-ci@master