name: Update Repl

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'rgxlog'
          destination-github-username: 'deanlight'
          destination-repository-name: 'spanner-workbench-live-repl'
          user-email: light.skep@gmail.com
          target-branch: main
          target-directory: content/rgxlog